config/routes.rb
Rails.application.routes.draw do
  resources :courses
  resources :students do
    get :courses, on: :member
    post :choose_courses, on: :member
  end

  root 'students#index', as: :root

end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  belongs_to :student
  belongs_to :course
end

app/models/course.rb
class Course < ActiveRecord::Base
  validates_presence_of :name, :description

  has_many :classrooms
  has_many :students, through: :classrooms
end

app/models/student.rb
class Student < ActiveRecord::Base
  validates_presence_of :name, :register_number
  validates_uniqueness_of :register_number

  has_many :classrooms
  has_many :courses, through: :classrooms

  def self.student_has_not_classrooms(student_id)
    classroom = Classroom.where(student_id: student_id)
    if classroom.empty?
      true
    else
      false
    end
  end

  def self.save_new_student_courses(student_id, course_ids)
    message = ''
    course_ids.each do |course_id|
      unless course_id.empty?
        classroom = Classroom.new
        classroom.student_id = student_id
        classroom.course_id = course_id
        classroom.entry_at = Time.new
        if classroom.save
          message = 'Courses are successfully chosen.'
        else
          message = 'Courses are not save.'
        end
      end
    end
    message
  end

  def self.update_student_courses(student_id, course_ids)
    Classroom.destroy_all(student_id: student_id)
    save_new_student_courses(student_id, course_ids)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :description, :status)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def courses
    @courses = Course.all
    @student = Student.find(params[:id])
  end

  def choose_courses
    course_ids = params[:student][:course_ids]
    student_id = params[:id]
    if Student.student_has_not_classrooms(student_id)
      flash[:notice] =  Student.save_new_student_courses(student_id, course_ids)
      redirect_to root_path
    else
      flash[:notice] =  Student.update_student_courses(student_id, course_ids)
      redirect_to root_path
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_student
    @student = Student.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def student_params
    params.require(:student).permit(:name, :register_number, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <!--<div class="field">-->
    <!-- <%= f.label :status %><br> -->
    <!--<%= f.number_field :status %>-->
  <!--</div>-->
  <div class="actions">
    <%= f.submit 'Send', :class => 'btn btn-primary btn-lg outline' %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course, :class => 'btn btn-primary btn-lg outline' %>
<%= link_to 'Back', courses_path, :class => 'btn btn-primary btn-lg outline' %>

app/views/courses/index.html.erb
<h1>Listing Courses</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td width="300px"><%= course.name %></td>
        <td><%= course.description %></td>
        <td class="acoes"><%= link_to 'Show', course, :class => 'btn btn-primary btn-lg outline' %></td>
        <td class="acoes"><%= link_to 'Edit', edit_course_path(course), :class => 'btn btn-primary btn-lg outline' %></td>
        <td class="acoes"><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-primary btn-lg outline' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path, :class => 'btn btn-primary btn-lg outline' %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path, :class => 'btn btn-primary btn-lg outline' %>

app/views/courses/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @course.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @course.description %>
</p>

<!--<p>-->
  <!--<strong>Status:</strong>-->
  <!--<%= @course.status %>-->
<!--</p>-->

<%= link_to 'Edit', edit_course_path(@course), :class => 'btn btn-primary btn-lg outline' %>
<%= link_to 'Back', courses_path, :class => 'btn btn-primary btn-lg outline' %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>SCHOOL</title>
  <%= stylesheet_link_tag    'application', :media => 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<script type="text/javascript">
    $(document).ready(function(){
        setTimeout(function(){
            $('.alert').remove();
        }, 2500);
    })
</script>
<body>
<nav class="navbar-inner">
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="brand">SCHOOL</div>
      <ul class="nav nav-pills">
        <li class="active"><a href="/students">Student</a></li>
        <li class="active"><a href="/courses">Courses</a></li>
      </ul>
    </div>
  </div>
  </div>
</nav>
<div id="main" role="main">
  <div class="container">
    <%= render 'layouts/messages' %>
    <br>
    <%= yield %>
  </div> <!--! end of .container -->
</div> <!--! end of #main -->
</body>
</html>

app/views/students/_form.html.erb
<script src="jquery.maskedinput.js" type="text/javascript"></script>
<script>
    jQuery(function($){
        $("#register").mask("999-9");
    });
</script>
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :register_number%><br>
    <%= f.text_field :register_number, :id => 'register'  %>
  </div>
  <!--<div class="field">-->
    <!-- <%= f.label :status %><br>-->
    <!--<%= f.number_field :status %>-->
  <!--</div>-->
  <div class="actions">
    <%= f.submit 'Send', :class => 'btn btn-primary btn-lg outline'  %>
  </div>
<% end %>

app/views/students/choose_courses.html.erb
<div><%= notice %></div>
<%= link_to 'Back', root_path %>

app/views/students/courses.html.erb
<%= form_for @student, :url => { :action => :choose_courses}, :html => { :method => 'post' } do |f| %>
    <% if @student.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@student.errors.count, 'error') %> prohibited this course from being saved:</h2>

          <ul>
            <% @student.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <h3>Student: <%= @student.name%><br></h3>

    <h3>Choose your courses</h3>

    <%= f.collection_check_boxes(:course_ids, Course.all, :id, :name) do |b| %>
        <%= b.label { b.check_box + b.text} %><br>
    <% end %>
    <br>
    <div class="actions">
      <%= submit_tag 'Send', :class => 'btn btn-primary btn-lg outline'  %>
    </div>
<% end %>

<%= link_to 'Back', root_path, :class => 'btn btn-primary btn-lg outline' %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student, :class => 'btn btn-primary btn-lg outline' %>
<%= link_to 'Back', students_path, :class => 'btn btn-primary btn-lg outline' %>

app/views/students/index.html.erb
<h1>Listing Students</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Register number</th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td width="300px"><%= student.register_number %></td>
        <td class="acoes"><%= link_to 'Show', student, :class => 'btn btn-primary btn-lg outline'  %></td>
        <td class="acoes"><%= link_to 'Edit', edit_student_path(student), :class => 'btn btn-primary btn-lg outline'  %></td>
        <td class="acoes"><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-primary btn-lg outline'  %></td>
        <td class="acoes"><%= link_to 'Choose courses', courses_student_path(student), :class => 'btn btn-primary btn-lg outline'  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path, :class => 'btn btn-primary btn-lg outline' %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path, :class => 'btn btn-primary btn-lg outline'  %>

app/views/students/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Register number:</strong>
  <%= @student.register_number %>
</p>

<!--<p>-->
  <!--<strong>Status:</strong>-->
  <!--<%= @student.status %>-->
<!--</p>-->

<%= link_to 'Edit', edit_student_path(@student), :class => 'btn btn-primary btn-lg outline' %>
<%= link_to 'Back', students_path, :class => 'btn btn-primary btn-lg outline' %>